# Generated by Django 3.1.7 on 2021-06-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210616_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option10',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option11',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option12',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option13',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option14',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option15',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option16',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option17',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option18',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option19',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option20',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option7',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option8',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option9',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question5',
        ),
    ]
