# Generated by Django 3.1.7 on 2021-06-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_answer_question_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='content',
        ),
    ]
